### ISSUE TITLE
Interprocedural CFG does not contain intra edges

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#68] opened 2023-09-13 06:21 UTC
There is possibly a mismatch of assumptions in the CFG construction and consumer of the CFGs, we expect `cfgNode.succ(false)` to return both the _inter_-procedural and _intra_-procedural edges so that it is possible to traverse the graph. 

See; `trait CfgNode` https://uq-pac.github.io/bil-to-boogie-translator/analysis/CfgNode.html#pred-0

See also `analysis/Dependencies.scala`; this is currently temporarily solved by unioning the edge sets together which is hacky and inefficient.

We should figure out which part of the code is responsible for maintaining this assumption/invariant.  

@yousifpatti do you have an example where the problem is visible, because for `functionpointer` the Dependencies hack doesn't seem to make any difference.  `run -a examples/functionpointer/functionpointer_clang.adt -r examples/functionpointer/functionpointer_clang.relf --analyse`. I think the CFG generator is _supposed_ to add intraprocedural edges to the interprocedural edge set, but haven't looked into it thoroughly.

**Comment by l-kent** [comment] 2023-09-13 06:34
duplicate of @60

**Comment by l-kent** [comment] 2023-09-13 06:34
Duplicate of #60

**Closed by l-kent** 2023-09-13 06:34 UTC
